---

- name: Ansible copy directory to the remote server
  hosts: appserver1
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: /mnt/data/jenkins/workspace/ansible-deploy/ansible/script/
      dest: /home/ubuntu/
      mode: a+w
    become: true    
  - name: Create and start Compose services
    docker_compose:
      project_src: /home/ubuntu/
      restarted: yes
      build: no
    register: output
    become: yes
  - debug:
      var: output
  become: yes          



#  - name: Prune everything
#    docker_prune:
#      images: yes
#    become: yes
#    register: output
#  - debug:
#      var: output


