---

- name: Ansible copy directory to the remote server
  hosts: appserver1
  tasks:
  - name: Ansible copy file to remote server
    copy:
      src: /mnt/data/jenkins/workspace/ansible-deploy/ansible/script/
      dest: /home/ubuntu/
      mode: a+w
    become: true    
  - name: Create and start Compose services
    docker_compose:
      project_src: /home/ubuntu/
      restarted: yes
      build: no
      detach: false
    register: docker_container_output
    #   become: yes            ------------- Do not use this!

  - name: Show test output
    debug:
      msg: "{{ docker_container_output.ansible_facts.docker_container.Output }}"
      

#    register: output
#  - debug:
#      var: output        



#  - name: Prune everything
#    docker_prune:
#      images: yes
#    become: yes
#    register: output
#  - debug:
#      var: output


