---

- name: Ansible copy directory to the remote server
  hosts: appserver1
  tasks:
  - docker_image:
        name: hello-world
        source: pull
  - name: Create and start Compose services
    docker_compose:
      project_src: /home/ubuntu
      restarted: yes
      build: no
    register: output
    become: yes
  - debug:
      var: output
