


- name: Install docker-compose python module
  pip:
    name: 
      - docker
      - docker-compose
    state: present
  become: yes

- name: Create and start Compose services
  docker_compose:
    project_src: /home/ubuntu/Docs/code
    state: present 
  register: output
  become: yes

- debug:
    var: output 
  
