---

- name: Ansible copy directory to the remote server
  hosts: appserver1
  tasks:  
  - name: Install docker-compose python module
    pip:
      name: 
        - docker
        - docker-compose
      state: present
    become: yes

  - name: Create and start Compose services
    docker_compose:
      project_src: /home/ubuntu
      state: present
    become: yes
    register: output
  - debug:
      var: output 
  


